name: quidalert_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - click==8.3.1
      - colorama==0.4.6
      - fastapi==0.124.4
      - greenlet==3.3.0
      - h11==0.16.0
      - idna==3.11
      - mako==1.3.10
      - markupsafe==3.0.3
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - sqlalchemy==2.0.45
      - sqlmodel==0.0.27
      - starlette==0.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
prefix: C:\Users\davide\miniconda3\envs\quidalert_env
